language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO=Django==1.4.10
  - DJANGO=Django==1.5.5
  - DJANGO=Django==1.6

matrix:
  allow_failures:
    # Allow failures for unreleased Django version
    # - env: DJANGO=https://www.djangoproject.com/m/releases/1.6/Django-1.6b4.tar.gz
    # Allow failures for Python 3
    - python: "3.2"
    - python: "3.3"
  exclude:
    # Django < 1.5 does not support Python 3
    - python: "3.2"
      env: DJANGO=Django==1.4.10
    - python: "3.3"
      env: DJANGO=Django==1.4.10


# command to install dependencies
install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors

# command to run tests
script: python setup.py test
