# X11 for headless UI tests
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=Django==1.4.5
  - DJANGO=Django==1.5.1

# command to install dependencies
install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - pip install -q https://github.com/praekelt/django-setuptest/archive/f4eacb4a929cdcc853a5c053c282dada5bdedc99.tar.gz --use-mirrors

# command to run tests
script: python setup.py test
